#!/usr/bin/env node
'use strict';
// Generate documentation/card-status.md from the code, so it cannot drift:
// config.js (registry flags), sets/*.js (definitions and unfinished markers),
// the card metadata (expected cards) and documentation/card-sets.md (the
// human playability decision). tests/card-status.test.js fails when the
// committed file differs from what this script generates.
//
//   node scripts/card-status.js           rewrite documentation/card-status.md
//   node scripts/card-status.js --check   exit 1 if it is out of date
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const outFile = path.join(root, 'documentation', 'card-status.md');
const DECISIONS = ['playable', 'in-progress', 'not-implemented', 'deprecated'];
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

// Placeholders written by scripts/scaffold_set.py. Ordinary developer TODOs in
// finished cards (for example AI improvement notes) are not unfinished work.
const SCAFFOLD_MARKER = new RegExp([
  'TODO: (Add the exact ELO|Implement effect|Add abilities or responseOn triggers|Add break and strength pump abilities)',
  '"\\.\\.\\."',
  'Resolve: function \\(\\) \\{ \\.\\.\\. \\}',
].join('|'));
const isScaffoldMarker = line => SCAFFOLD_MARKER.test(line);

function registry() {
  const context = {console};
  vm.createContext(context);
  vm.runInContext(read('config.js'), context, {filename: 'config.js'});
  return context.setRegistry;
}

function decisions() {
  const rows = new Map();
  for (const m of read('documentation/card-sets.md').matchAll(/^\|\s*`?(\w+)`?\s*\|\s*([\w-]+)\s*\|(.*)\|\s*$/gm)) {
    if (m[1] !== 'Set' && DECISIONS.includes(m[2])) rows.set(m[1], m[2]);
  }
  return rows;
}

function definitions(file) {
  const lines = read(file).split('\n');
  const starts = [];
  lines.forEach((line, i) => { const m = line.match(/^(?:cardSet|coreSet)\[(\d+)\]\s*=/); if (m) starts.push([m[1], i]); });
  return new Map(starts.map(([id, start], k) => {
    const end = k + 1 < starts.length ? starts[k + 1][1] : lines.length;
    return [String(Number(id)), lines.slice(start, end).filter(isScaffoldMarker).length];
  }));
}

function generate() {
  const reg = registry();
  const decided = decisions();
  const metadata = JSON.parse(read('carddata/carddata.json')).data;
  const sets = Object.entries(reg.availableSets).map(([key, set]) => {
    const file = 'sets/' + set.file + '.js';
    const defs = fs.existsSync(path.join(root, file)) ? definitions(file) : new Map();
    const [lo, hi] = set.idRange || [0, -1];
    const cards = metadata.filter(card => /^\d+$/.test(card.code) && +card.code >= lo && +card.code <= hi)
      .sort((a, b) => +a.code - +b.code);
    const id = card => String(Number(card.code));
    const missing = cards.filter(card => !defs.has(id(card)));
    const unfinished = cards.filter(card => defs.get(id(card)) > 0);
    return {key, set, file, decision: decided.get(key) || '(none)', cards, defs, missing, unfinished,
      launcher: (reg.decklauncherSets || []).includes(key)};
  });

  const out = [];
  out.push('# Card status', '');
  out.push('> Generated by `node scripts/card-status.js` from `config.js`, `sets/*.js`, the card');
  out.push('> metadata and [card-sets.md](card-sets.md). Do not edit by hand:');
  out.push('> `tests/card-status.test.js` fails when this file is out of date.', '');
  out.push('"Unfinished" means the definition still contains a placeholder written by');
  out.push('`scripts/scaffold_set.py`. A set with no unfinished markers can still be incomplete,');
  out.push('which is why playability is a decision recorded in card-sets.md.', '');
  out.push('## Sets', '');
  out.push('| Set | Decision | Cards | Defined | Missing | Unfinished | config.js hidden / untested | Deck launcher |');
  out.push('|---|---|---:|---:|---:|---:|---|---|');
  for (const s of sets) {
    out.push('| `' + s.key + '` | ' + s.decision + ' | ' + s.cards.length + ' | ' + s.defs.size + ' | ' +
      s.missing.length + ' | ' + s.unfinished.length + ' | ' + s.set.hidden + ' / ' + s.set.untested + ' | ' +
      (s.launcher ? 'yes' : 'no') + ' |');
  }

  const mismatches = [];
  for (const s of sets) {
    const offered = s.set.hidden === false || s.launcher;
    if (s.decision === '(none)') mismatches.push('`' + s.key + '` has no decision in card-sets.md.');
    if (s.decision === 'playable' && (s.set.hidden || s.set.untested))
      mismatches.push('`' + s.key + '` is playable, but config.js marks it hidden: ' + s.set.hidden + ', untested: ' + s.set.untested + '.');
    if (['not-implemented', 'deprecated'].includes(s.decision) && offered)
      mismatches.push('`' + s.key + '` is ' + s.decision + ', but config.js offers it to players (hidden: ' + s.set.hidden +
        (s.launcher ? ', in decklauncherSets' : '') + ').');
    if (s.decision === 'playable' && (s.missing.length || s.unfinished.length))
      mismatches.push('`' + s.key + '` is playable with ' + s.missing.length + ' missing and ' + s.unfinished.length + ' unfinished cards.');
  }
  out.push('', '## Mismatches to review', '');
  out.push(...(mismatches.length ? mismatches.map(m => '- ' + m) : ['None.']));

  out.push('', '## Missing and unfinished cards in playable and in-progress sets');
  for (const s of sets.filter(entry => ['playable', 'in-progress'].includes(entry.decision))) {
    out.push('', '### `' + s.key + '` (' + s.file + ')', '');
    if (!s.missing.length && !s.unfinished.length) { out.push('None.'); continue; }
    for (const card of s.missing) out.push('- ' + card.code + ' ' + card.title + ': no definition');
    for (const card of s.unfinished) out.push('- ' + card.code + ' ' + card.title + ': ' + s.defs.get(String(Number(card.code))) + ' unfinished marker(s)');
  }
  return out.join('\n') + '\n';
}

module.exports = {generate, outFile, isScaffoldMarker};

if (require.main === module) {
  const text = generate();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : '';
    if (current !== text) { console.log('documentation/card-status.md is out of date; run node scripts/card-status.js'); process.exitCode = 1; }
    else console.log('documentation/card-status.md is up to date.');
  } else {
    fs.writeFileSync(outFile, text);
    console.log('Wrote documentation/card-status.md');
  }
}
